###
POST http://localhost:3000/auth
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "teste"
}


###
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE

{
    "title": "ir para a feira",
    "status": "feito",
    "description": "comprar verduras",
    "priority": 4
}



###
GET http://localhost:3000/tasks?colors=Vermelho,Rosa


###
GET http://localhost:3000/tasks/5

###
PATCH http://localhost:3000/tasks/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE

{
    "title": "armazem",
    "status": "em andamento",
    "description": "encher o regador até 250 ml e regar o jardim do pátio á ao campo de futebol",
    "priority": 5
}

###
DELETE http://localhost:3000/tasks/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE






###
POST http://localhost:3000/tasks/5/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE

{
    "cor": "Azul",
    "name": "Comemoração"
  
}


###
GET http://localhost:3000/5/tags

###
GET http://localhost:3000/5/tags/7


###
PATCH http://localhost:3000/5/tags/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE

{
    "cor": "Laranja",
    "name": "Cartao lembrete"
  
}

###
DELETE http://localhost:3000/5/tags/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1ODEyNzQyLCJleHAiOjE2ODY0MTc1NDJ9.-6i-h_g2IRRrgZrvFIFrOewBFc6zMuxsMxHcJKCrXsE
